// The class-name ignorer Stryker loads as a plugin — generated file content,
// not scaffolding logic, and the one step people skipped when the CLI printed
// steps instead of writing files.
//
// IGNORER_VERSION is what tells an existing install its copy is stale, so bump
// it whenever the body changes or nobody gets the fix.


// Bumped whenever IGNORER changes. A project scaffolded before a rule existed
// has no other way to learn about it, and the file is generated, not authored —
// so a missing marker means overwrite, not keep.
export const IGNORER_VERSION = "v3";

// .mjs, not .js: an app without "type": "module" in its package.json cannot
// load ESM from a .js file, and the plugin is ESM.
export const IGNORER = `// Generated by @spardutti/claude-skills — ignorer ${IGNORER_VERSION}. Edits are
// overwritten when the rules change.
//
// Ignore by WHERE the mutant sits, not by what kind it is. Disabling the
// StringLiteral mutator globally would also stop mutating labels, keys and
// separators — strings whose value is behaviour.
//
// Content in a module-level table is NOT handled here. Those are static mutants,
// and \`ignoreStatic\` in stryker.config.json covers them for less.
import { PluginKind, declareValuePlugin } from "@stryker-mutator/api/plugin";

export const strykerPlugins = [
  declareValuePlugin(PluginKind.Ignore, "tailwind-classnames", {
    shouldIgnore(path) {
      if (path.find((p) => p.isJSXAttribute() && p.node.name.name === "className"))
        return "styling, not behaviour";
      if (path.find((p) => p.isCallExpression() && p.node.callee.name === "cn"))
        return "styling, not behaviour";
    },
  }),
];
`;
